### ISSUE TITLE
How do I use default_path()?

### ISSUE THREAD

**Issue by jcbhmr** [btzy/nfde-rs#48]
Hello! 👋

FULL DISCLOSURE: I'm **extremely new** to using Rust. this is the first spot I've asked this question. I'm still googling after asking this and might solve it on my own 😂

I want to do something like this sorta like from the example, just using a default_path():

```rs
use nfde::*;

fn main() -> Result<(), nfde::Error> {
    // Initialize NFD... NFD will be automatically deinitialized when this object is destroyed
    let nfd = Nfd::new()?;

    // Show the dialog...
    // Note: .show() will block until the dialog is closed
    // You can also set a default path using .default_path(Path)
    let res = nfd
        .open_file()
        .default_path("/home/jcbhmr") // 👈 How do I do this?
        .add_filter("Source code", "c,cpp,cc")?
        .add_filter("Headers", "h,hpp")?
        .show();

    match res {
        DialogResult::Ok(path_buf) => {
            println!("Success!");
            println!("Path: {}", path_buf.display());
        }
        DialogResult::Cancel => {
            println!("User pressed cancel.");
        }
        DialogResult::Err(error_str) => {
            println!("Error: {}", error_str);
        }
    };

    Ok(())
}
```

Actual complete context:

![image](https://github.com/btzy/nfde-rs/assets/61068799/07341f63-fffb-454c-8950-5429e14e7d52)
https://github.com/jcbhmr/nfde.node

I will close this if I figure out how to do this **extremely basic** thing in Rust 😂
Sorry for wasting your time lmao

Sidenote: It might be good to use this in one of the examples? 🤔

**Comment by jcbhmr** [comment]
Ok so I got completely baffled by the fact that on the docs.rs page it says you need to pass aa `AsRef<Path>` thing. I though that meant I would need to construct that all myself?

![image](https://github.com/btzy/nfde-rs/assets/61068799/193cfcf5-f50c-4ada-bd44-befb1fb5494f)
Like I would need to somehow get `path` to be of type `AsRef<Path>` in this code:

```rs
let path = ... some magic to get AsRef<Path>
x.default_path(path);
```

Turns out NO you literally just pass in a string 🤣 BUT it needs to be the UPPERCASE String not the str slice thingie of known length.
![image](https://github.com/btzy/nfde-rs/assets/61068799/8f90eeef-8377-4d05-aa53-f35deba30d89)

**Comment by btzy** [comment]
Hey, thanks for trying this out!  There was a bug in the library, which I've now fixed with https://github.com/btzy/nfde-rs/commit/8c5bbfe1dac8bee7562675ef319d6534f1e2a379.

[`AsRef<Path>`](https://doc.rust-lang.org/std/convert/trait.AsRef.html) is a trait that applies to the reference (i.e. `&str` or `&Path`) instead of the unsized type itself (i.e. `str` and `Path`), and so the old code with the argument `path: &P` means that `path` is a reference to another reference, thereby causing the compile error when you try to pass it a `&str` or `&Path`.

With the fix, you should be able to do `.default_path("/home/jcbhmr")` and `.default_path(Path::new("/home/jcbhmr"))` without issues.
